DROP TABLE IF EXISTS users, items, bookings, requests, comments cascade;
CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     owner INTEGER NOT NULL,
                                     name  VARCHAR(255) NOT NULL,
                                     description TEXT,
                                     available    BOOLEAN,
                                     item_request INTEGER,
                                     constraint ITEMS_USERS_USER_ID_FK
                                         foreign key (owner) references USERS (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
                                     request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     description TEXT NOT NULL,
                                     requestor_id INTEGER NOT NULL,
                                     created timestamp,
                                     constraint ITEMS_REQUEST_USERS_USER_ID_FK
                                         foreign key (requestor_id) references USERS (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
                                     booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     start_time timestamp,
                                     end_time timestamp,
                                     item INTEGER NOT NULL,
                                     booker INTEGER NOT NULL,
                                     status VARCHAR(15),
                                     constraint BOOKINGS_USERS_USER_ID_FK
                                         foreign key (booker) references USERS (user_id) ON DELETE CASCADE,
                                     constraint BOOKINGS_ITEMS_ITEM_ID_FK
                                         foreign key (item) references ITEMS (item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
                                        comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text TEXT NOT NULL,
                                        item_id INTEGER NOT NULL,
                                        author_id INTEGER NOT NULL,
                                        created timestamp,
                                        constraint COMMENTS_USERS_USER_ID_FK
                                            foreign key (author_id) references USERS (user_id) ON DELETE CASCADE,
                                        constraint COMMENTS_ITEMS_ITEM_ID_FK
                                            foreign key (item_id) references ITEMS (item_id) ON DELETE CASCADE
);